name: frontend

on:
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  Web-App:
    name: web-app
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - uses: c-hive/gha-npm-cache@v1
        with:
          directory: web-app

      - name: install
        run: |
          cd web-app/
          npm install

      - name: lint
        run: |
          cd web-app/
          npm run lint
          
      - name: test
        run: |
          cd web-app/
          npm run test
          
  Ionic-App:
    name: ionic-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: c-hive/gha-npm-cache@v1
        with:
          directory: ionic-app

      - name: install
        run: |
          cd ionic-app/
          npm install

      - name: lint
        run: |
          cd ionic-app/
          npm run lint
