name: frontend

on:
  pull_request:
    branches: [ master ]

jobs:
  Web-App:
    name: web-app
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: check cache
        id: cache-web
        uses: actions/cache@v2
        with:
          path: cache-web
          key: ${{ runner.os }}-cache-web

      - name: install
        if: steps.cache-web.outputs.cache-hit != 'true'
        run: |
            cd web-app/
            npm ci
      - name: lint
        run: |
          cd web-app/
          npm run lint
      - name: build
        run: |
          cd web-app/
          npm run build
      - name: build-storybook
        run: |
          cd web-app/
          npm run build-storybook
          
  Ionic-App:
    name: ionic-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: check cache
        id: cache-ionic
        uses: actions/cache@v2
        with:
          path: cache-ionic
          key: ${{ runner.os }}-cache-ionic

      - name: install
        if: steps.cache-ionic.outputs.cache-hit != 'true'
        run: |
            cd ionic-app/
            npm ci
      - name: lint
        run: |
          cd ionic-app/
          npm run lint
      - name: build
        run: |
          cd ionic-app/
          npm run build       
